#162948977 Write unit tests for ALL existing functionality
andela/ah-fulldeck pull request #10
Opened 2019-01-15 12:19 UTC by JoshuaKodhe

#### What does this PR do?

Have tests for the existing functionality

#### Description of Task to be completed?

Have tests for the Login functionality 
Have tests for the Signup functionality 
Have tests for the User model 

#### How should this be manually tested?
After cloning the repo using `git clone https://github.com/andela/ah-fulldeck.git`
Checkout this branch `ch-test-existing-functionality-162948977` using the command
`git checkout ch-test-existing-functionality-162948977`
Run the tests using the command `python manage.py test`

#### What are the relevant pivotal tracker stories?

[#162948977 ](https://www.pivotaltracker.com/story/show/162948977)

#### Screenshots (if appropriate)
<img width="930" alt="screenshot 2019-01-15 at 15 18 18" src="https://user-images.githubusercontent.com/43740193/51180218-dbbb5280-18d8-11e9-8be3-06b540a1a3de.png">

2019-01-15 14:23 UTC, Nicanor008 commented
I like how you have done your tests, am getting some ideas on how I'll implement my task from your files.

2019-01-15 14:27 UTC, Hesbon5600 commented
I like the idea of having a separate file for the base test.  
Great implementation of tests for the  models  💪

2019-01-15 17:29 UTC, eduhmik commented on authors/apps/authentication/tests/test_login.py
> +        self.assertIn(b'This field is require', response.content)
Kindly amend the message in assertIn

2019-01-15 17:29 UTC, eduhmik commented on authors/apps/authentication/tests/test_login.py
> +        self.assertIn(b'This field is require', response.content)
Here too

2019-01-15 17:48 UTC, charitymarani commented
@JoshuaKodhe Could you test unregistered user trying to log in or is that @Hesbon5600 's task?

2019-01-16 07:38 UTC, kzyangiro requested changes
@JoshuaKodhe Kindly clear the Base app and move the welcome message to auth, then point the testing to all remaining apps, not only Authentication

2019-01-16 07:41 UTC, kzyGit commented on authors/apps/authentication/tests/test_signup.py
> +        self.assertIn(b'This field is required', response.content)
@JoshuaKodhe This chunk of code is duplicated in about 4 or 5 more places. We need to be very keen on maintainability, create a single function/method that does this, then call it in all the relevant areas to reduce code duplication

2019-01-16 14:06 UTC, kzyGit commented on authors/urls.py
> +    path('', include('authors.apps.authentication.urls')),
@JoshuaKodhe Why did you name it app_authentication rather than just authentication?

2019-01-17 04:17 UTC, kzyangiro approved these changes

2019-01-17 04:17 UTC, merged