#162948994 User should be able to create articles
andela/ah-fulldeck pull request #16
Opened 2019-01-22 09:44 UTC by Hesbon5600

**What does this PR do?**
 _A user should be able to:_
- Create an article
- Retrieve all articles
- Retrieve one article
- Edit an article he/she created
- Delete an article he/she created

**How should this be manually tested?**

1. Run the server:
`python manage.py runserver`

1. From postman:

    1. Create an article by sending a `post` request to the '/api/v1/articles/' end point with the data body 
    ```source-json
    {
        "article": {
        "title": "Test Article",
        "description": "Test description for the article",
        "body": "Test body for the article"
        }
    }
    ```
    2. Retrieve all articles by sending a `get` request to the  '/api/v1/articles/' end point
    3. Retrieve a single article by sending a `get` request to the  '/api/v1/articles/`<slug>`/' end point and pass the articles's slug in the url
    4. Update an  article by sending a `put` request to the  '/api/v1/articles/`<slug>`/' end point and pass the articles's slug in the url. Pass the following as the body
    ``` source-json
    {
    "article": {
        "title": "Updated title",
        "description": "Updated description",
        "body": "Updated body"
    }
    }
    ```
    5. Delete an  article by sending a `delete` request to the  '/api/v1/articles/`<slug>`/' end point

**Any background context you want to provide?**  
None

**What are the relevant pivotal tracker stories?**
[#162948994](https://www.pivotaltracker.com/story/show/162948994)

**Screenshots**
   1. Create an article
<img width="965" alt="screenshot 2019-01-22 at 12 34 09" src="https://user-images.githubusercontent.com/32098817/51525794-1e81ab00-1e42-11e9-9caa-2e900f345966.png">
   2. Retrieve all articles
<img width="975" alt="screenshot 2019-01-22 at 12 35 50" src="https://user-images.githubusercontent.com/32098817/51525902-453fe180-1e42-11e9-8667-0a98d77f7fdb.png">
   3. Retrieve one article
<img width="959" alt="screenshot 2019-01-22 at 12 36 42" src="https://user-images.githubusercontent.com/32098817/51525954-66083700-1e42-11e9-8d5f-3099c77d5fee.png">
   4. Update an article
<img width="968" alt="screenshot 2019-01-22 at 12 39 17" src="https://user-images.githubusercontent.com/32098817/51526151-c4351a00-1e42-11e9-82f0-7fc30f8368bb.png">
   5. Delete an article
<img width="940" alt="screenshot 2019-01-22 at 12 40 37" src="https://user-images.githubusercontent.com/32098817/51526232-f5ade580-1e42-11e9-90df-f97750765a66.png">

2019-01-22 10:08 UTC, Nyakaru requested changes
@Hesbon5600 Kindly squash your commits into one

2019-01-22 13:26 UTC, kzyangiro requested changes
You need to have only one migration file. @Hesbon5600

2019-01-22 13:35 UTC, kzyGit commented on authors/apps/articles/tests/test_articles.py
> +
Duplicate here @Hesbon5600

2019-01-22 13:35 UTC, kzyGit commented on authors/apps/articles/views.py
> +# from django.contrib.auth.models import AnonymousUser
Remove unnecessary comments

2019-01-22 13:41 UTC, Nyakaru approved these changes

2019-01-24 08:59 UTC, kzyGit commented on authors/apps/articles/views.py
> +# from django.contrib.auth.models import AnonymousUser
You are nolonger using this comment, kindly remove it. @Hesbon5600

2019-01-24 09:11 UTC, JoshuaKodhe approved these changes
The update image url has been fixed and work as should

2019-01-24 09:16 UTC, kzyangiro approved these changes

2019-01-24 09:16 UTC, merged