#162949003 Implement pagination
andela/ah-fulldeck pull request #25
Opened 2019-01-28 16:15 UTC by JoshuaKodhe

### What does this PR do?

Have pagination support for articles

### Description of Task to be completed?

Have pagination functionality

### How should this be manually tested?
**Run the server:**
`python manage.py runserver`

**From postman:**
    1. Create multiple articles by sending  `post` requests to the '/api/v1/articles/' endpoint with the data body 
    ```source-json
    {
        "article": {
        "title": "Test Article",
        "description": "Test description for the article",
        "body": "Test body for the article"
        }
    }
    ```

2. Retrieve all articles by sending a `get` request to the  '/api/v1/articles/' endpoint

```source-json
{
    "article": {
        "count": 2,
        "next": "http://127.0.0.1:8000/api/v1/articles/?page=2",
        "previous": null,
        "results": [
            {
                "title": "How to train your dragon",
                "description": "Ever wonder how?",
                "body": "It takes a Jacobian",
                "slug": "how-to-train-your-dragon-1",
                "avg_rating": {
                    "avg_rating": 0,
                    "total_user_rates": 0,
                    "each_rating": {}
                },
                "image_url": null,
                "author": {
                    "username": "joe",
                    "bio": "",
                    "image": "https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/user.png"
                },
                "created_at": "2019-01-28T09:30:06.694979Z",
                "updated_at": "2019-01-28T09:30:06.695002Z"
            }
        ]
    }
}
```

### What are the relevant pivotal tracker stories?
[#162949003](https://www.pivotaltracker.com/story/show/162949003)

### Screenshots
<img width="953" alt="screenshot 2019-01-28 at 19 12 32" src="https://user-images.githubusercontent.com/43740193/51849446-cb6f9280-2330-11e9-972a-4079a054942c.png">

2019-01-29 09:33 UTC, Nicanor008 reviewed
I like how you use standard pagination in a simple way.This can also be re-used in future for displaying authors

2019-01-29 09:47 UTC, Hesbon5600 reviewed
Tested the PR and it looks amazing

2019-01-29 11:26 UTC, eduhmik commented on authors/settings.py
> +PAGE_SIZE = os.getenv("PAGE_SIZE")
Hey @JoshuaKodhe great way of implementing pagination, allows us to quickly change page size from our environment variable

2019-01-29 11:48 UTC, kzyangiro requested changes
@JoshuaKodhe Page size should not be in the settings/environment. Set a default page size i.e 10, then let users to be able to give the **page** - i.e page 2 and **page size** - Number of items to display in the page. These two vars should be passed by a user as params

You can then add about 15 items and test out what displays in page 1 and page 2 given a particular set of parameters, and show us the screenshot

2019-01-29 12:03 UTC, Nyakaru commented on authors/apps/articles/tests/test_pagination.py
> +        self.assertEqual(21, response.data['count'])
Good use of DRY code.

2019-01-30 10:21 UTC, kzyangiro approved these changes

2019-01-30 10:21 UTC, merged