#162949007 Enable bookmarking of articles
andela/ah-fulldeck pull request #28
Opened 2019-01-29 14:33 UTC by charitymarani

**What does this PR do?**

1. Adds  endpoints to bookmark ,unbookmark and fetch bokmarked articles

Endpoints involved:
```
PUT  /api/v1/articles/<slug>/bookmark/
GET  /api/v1/articles/bookmarks/
```

2. Adds tests for bookmarking articles

**How to manually test these features**
Clone this Repo
`git checkout ft-bookmark-articles-162949007`
Make Migrations
Run the server
Register users and Add an article
Test the bookmark endpoints on postman
**NB**
The functionality for bookmarking and unbookmarking works like a toggle

**Description of tasks to be completed**
-Users should be able to bookmark articles for reading later
-Users should be to  remove articles from bookmarks
- Users should be able to fetch all their bookmarked articles

**Relevant pivotal tracker stories**
[#162949007](https://www.pivotaltracker.com/story/show/162949007)
**Screenshots**

**Bookmark an article**

<img width="1181" alt="screenshot 2019-01-29 at 17 13 05" src="https://user-images.githubusercontent.com/25352662/51914718-890a8c00-23ea-11e9-9351-71f670aca7bb.png">

**Remove article from bookmarks**

<img width="1180" alt="screenshot 2019-01-29 at 17 13 21" src="https://user-images.githubusercontent.com/25352662/51914784-a3dd0080-23ea-11e9-9cdd-a90b373a1a51.png">

**Fetch all bookmarked articles for a specific user**

<img width="1180" alt="screenshot 2019-01-29 at 17 12 14" src="https://user-images.githubusercontent.com/25352662/51914832-c3742900-23ea-11e9-8fdb-2688d88cf70c.png">

**User can't bookmark non-existing article**

<img width="1180" alt="screenshot 2019-01-29 at 17 14 02" src="https://user-images.githubusercontent.com/25352662/51914881-dedf3400-23ea-11e9-85c8-efd25bf5be11.png">

2019-01-29 17:40 UTC, eduhmik reviewed
Hey @Charity, please do not push to your PR migrations and any files you have not changed. @Kezzy has advised us to only add the specific files we have modified only next time

2019-01-29 17:42 UTC, Hesbon5600 reviewed
Hey, I have a suggestion. Instead of just 'Article has been bookmarked!', could the message include the article itself

2019-01-30 06:45 UTC, Nicanor008 commented on authors/apps/articles/tests/base_test.py
> +    def authorize(self):
intelligent way of abstracting user authorization

2019-01-30 06:55 UTC, charitymarani commented
> Hey, I have a suggestion. Instead of just 'Article has been bookmarked!', could the message include the article itself

Fixed this @Hesbon5600

2019-01-30 09:03 UTC, charitymarani commented
> Hey @charity, please do not push to your PR migrations and any files you have not changed. @kezzy has advised us to only add the specific files we have modified only next time

@eduhmik Fixed this

2019-01-30 10:35 UTC, Nyakaru approved these changes

2019-01-30 10:59 UTC, kzyangiro requested changes
@charitymarani Remove profiles migrations.

2019-01-30 11:07 UTC, charitymarani commented
> @charitymarani Remove profiles migrations.

@kzyGit I made changes to profile model so the migrations are modified

2019-01-30 11:15 UTC, kzyangiro approved these changes

2019-01-30 11:15 UTC, merged